modLoader = "kotlinforforge" #mandatory
loaderVersion = "[3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]] #mandatory
modId = "soluna" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Soluna" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile = "examplemod.png" #optional
credits = "hkmod" #optional
authors = "tmvkrpxl0, PleahMaCaka" #optional
description = '''
Magic mod based on vanilla style, written by HKMOD group
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.soluna]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.soluna]]
modId = "minecraft"
mandatory = false # LOL
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
